import type { ParticleConfig } from "./particle-types"

export const PRESETS: Array<{
  name: string
  config: ParticleConfig
}> = [
  {
    name: "Drift",
    config: {
      count: 100,
      speed: 0.3,
      size: 1.5,
      life: 150,
      gravity: 0.05,
      friction: 0.985,
      spread: 8,
      colorHue: 280,
      colorSaturation: 60,
      colorLightness: 60,
      trailLength: 25,
      explosiveForce: 2,
      emissionRate: 0.2,
      gridDensity: 0,
      waveAmplitude: 0,
      waveFrequency: 0.05,
      waveSpeed: 1,
      waveCount: 1,
      particleColor: "#b084cc",
      backgroundColor: "#1a1a2e",
      cameraAngle: 30,
      particleGlow: false,
      backgroundGradient: "#0f3460",
    },
  },
  {
    name: "Burst",
    config: {
      count: 250,
      speed: 3,
      size: 3,
      life: 80,
      gravity: 0.3,
      friction: 0.96,
      spread: 1,
      colorHue: 40,
      colorSaturation: 100,
      colorLightness: 55,
      trailLength: 10,
      explosiveForce: 12,
      emissionRate: 0.8,
      gridDensity: 0,
      waveAmplitude: 0,
      waveFrequency: 0.05,
      waveSpeed: 1,
      waveCount: 1,
      particleColor: "#ff6b35",
      backgroundColor: "#1a1a1a",
      cameraAngle: 30,
      particleGlow: false,
      backgroundGradient: "#2a2a2a",
    },
  },
  {
    name: "Rain",
    config: {
      count: 200,
      speed: 1,
      size: 1,
      life: 120,
      gravity: 0.2,
      friction: 0.975,
      spread: 6,
      colorHue: 200,
      colorSaturation: 80,
      colorLightness: 65,
      trailLength: 30,
      explosiveForce: 0.8,
      emissionRate: 0.5,
      gridDensity: 0,
      waveAmplitude: 0,
      waveFrequency: 0.05,
      waveSpeed: 1,
      waveCount: 1,
      particleColor: "#4dc3f7",
      backgroundColor: "#0d47a1",
      cameraAngle: 30,
      particleGlow: false,
      backgroundGradient: "#1565c0",
    },
  },
  {
    name: "Cosmic",
    config: {
      count: 150,
      speed: 1.5,
      size: 2.5,
      life: 200,
      gravity: 0,
      friction: 0.99,
      spread: 3,
      colorHue: 270,
      colorSaturation: 90,
      colorLightness: 60,
      trailLength: 40,
      explosiveForce: 3,
      emissionRate: 0.3,
      gridDensity: 0,
      waveAmplitude: 0,
      waveFrequency: 0.05,
      waveSpeed: 1,
      waveCount: 1,
      particleColor: "#b39ddb",
      backgroundColor: "#1a0033",
      cameraAngle: 30,
      particleGlow: false,
      backgroundGradient: "#331a66",
    },
  },
  {
    name: "Ember",
    config: {
      count: 120,
      speed: 2,
      size: 2,
      life: 100,
      gravity: 0.15,
      friction: 0.98,
      spread: 2,
      colorHue: 20,
      colorSaturation: 100,
      colorLightness: 50,
      trailLength: 8,
      explosiveForce: 8,
      emissionRate: 0.4,
      gridDensity: 0,
      waveAmplitude: 0,
      waveFrequency: 0.05,
      waveSpeed: 1,
      waveCount: 1,
      particleColor: "#ff6f00",
      backgroundColor: "#0d0d0d",
      cameraAngle: 30,
      particleGlow: false,
      backgroundGradient: "#1a0000",
    },
  },
  {
    name: "Void",
    config: {
      count: 80,
      speed: 0.5,
      size: 1,
      life: 180,
      gravity: 0,
      friction: 0.995,
      spread: 10,
      colorHue: 0,
      colorSaturation: 0,
      colorLightness: 70,
      trailLength: 50,
      explosiveForce: 1,
      emissionRate: 0.15,
      gridDensity: 0,
      waveAmplitude: 0,
      waveFrequency: 0.05,
      waveSpeed: 1,
      waveCount: 1,
      particleColor: "#e0e0e0",
      backgroundColor: "#0a0a0a",
      cameraAngle: 30,
      particleGlow: false,
      backgroundGradient: "#1a1a1a",
    },
  },
  {
    name: "Ocean",
    config: {
      count: 150,
      speed: 1,
      size: 2,
      life: 100,
      gravity: 0.1,
      friction: 0.98,
      spread: 2,
      colorHue: 0,
      colorSaturation: 100,
      colorLightness: 50,
      trailLength: 15,
      explosiveForce: 5,
      emissionRate: 0.3,
      gridDensity: 15,
      waveAmplitude: 0.25,
      waveFrequency: 0.05,
      waveSpeed: 1.2,
      waveCount: 3,
      particleColor: "#82ccdd",
      backgroundColor: "#0a3d62",
      cameraAngle: 30,
      particleGlow: true,
      backgroundGradient: "#3c6382",
    },
  },
  {
    name: "Sunset",
    config: {
      count: 150,
      speed: 1,
      size: 2,
      life: 100,
      gravity: 0.1,
      friction: 0.98,
      spread: 2,
      colorHue: 0,
      colorSaturation: 100,
      colorLightness: 50,
      trailLength: 15,
      explosiveForce: 5,
      emissionRate: 0.3,
      gridDensity: 12,
      waveAmplitude: 0.3,
      waveFrequency: 0.04,
      waveSpeed: 0.8,
      waveCount: 2,
      particleColor: "#ff9a76",
      backgroundColor: "#2d1810",
      cameraAngle: 35,
      particleGlow: true,
      backgroundGradient: "#663d3d",
    },
  },
]
