import type { ParticleConfig } from "@/lib/particle-types"

export const presets: Array<{ name: string; id: string; config: ParticleConfig }> = [
  {
    name: "Default",
    id: "default",
    config: {
      size: 1,
      gridDensity: 233,
      waveAmplitude: 0.95,
      waveFrequency: 0.01,
      waveSpeed: 0.1,
      waveCount: 1,
      waveDirection: 229,
      cameraRoll: 0,
      cameraPitch: -6,
      cameraAltitude: 240,
      colorMode: "solid",
      particleColor: "#ff00ff",
      peakColor: "#00ffff",
      troughColor: "#ff00ff",
      backgroundColor: "#0a0a0a",
      backgroundGradient: "#1a1a2e",
    },
  },
  {
    name: "Party Wave",
    id: "party-wave",
    config: {
      size: 1,
      gridDensity: 143,
      waveAmplitude: 1,
      waveFrequency: 0.5,
      waveSpeed: 0.1,
      waveCount: 3,
      waveDirection: 220,
      cameraRoll: -8,
      cameraPitch: -72,
      cameraAltitude: 1000,
      colorMode: "gradient",
      particleColor: "#ff00ff",
      peakColor: "#00ffff",
      troughColor: "#ff00ff",
      backgroundColor: "#0a0a0a",
      backgroundGradient: "#1a1a2e",
    },
  },
  {
    name: "Ocean Depths",
    id: "ocean-depths",
    config: {
      size: 1.5,
      gridDensity: 200,
      waveAmplitude: 0.95,
      waveFrequency: 0.39,
      waveSpeed: 0.1,
      waveCount: 3,
      waveDirection: 155,
      cameraRoll: -151,
      cameraPitch: -61,
      cameraAltitude: -430,
      colorMode: "gradient",
      particleColor: "#0099ff",
      peakColor: "#00ffff",
      troughColor: "#000033",
      backgroundColor: "#000814",
      backgroundGradient: "#001d3d",
    },
  },
  {
    name: "Neon Tsunami",
    id: "neon-tsunami",
    config: {
      size: 10,
      gridDensity: 193,
      waveAmplitude: 0.8,
      waveFrequency: 0.15,
      waveSpeed: 0.1,
      waveCount: 2,
      waveDirection: 210,
      cameraRoll: 8,
      cameraPitch: -60,
      cameraAltitude: 1000,
      colorMode: "gradient",
      particleColor: "#ff00ff",
      peakColor: "#00e1ff",
      troughColor: "#c800ff",
      backgroundColor: "#f70295",
      backgroundGradient: "#6f0778",
    },
  },
  {
    name: "Ripple",
    id: "ripple",
    config: {
      size: 1,
      gridDensity: 150,
      waveAmplitude: 0.5,
      waveFrequency: 0.01,
      waveSpeed: 0.3,
      waveCount: 5,
      waveDirection: 138,
      cameraRoll: -9,
      cameraPitch: -83,
      cameraAltitude: 1000,
      colorMode: "gradient",
      particleColor: "#ffffff",
      peakColor: "#ffffff",
      troughColor: "#666666",
      backgroundColor: "#0a0a0a",
      backgroundGradient: "#1a1a1a",
    },
  },
  {
    name: "Aurora",
    id: "aurora",
    config: {
      size: 1,
      gridDensity: 200,
      waveAmplitude: 1,
      waveFrequency: 0.5,
      waveSpeed: 0.1,
      waveCount: 5,
      waveDirection: 330,
      cameraRoll: 8,
      cameraPitch: -7,
      cameraAltitude: 880,
      colorMode: "gradient",
      particleColor: "#00ff00",
      peakColor: "#00ff88",
      troughColor: "#8800ff",
      backgroundColor: "#000a1a",
      backgroundGradient: "#001a33",
    },
  },
]

